name: macOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DYLD_LIBRARY_PATH: /Applications/Xcode_13.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib
  
jobs:
  build:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
